<div style="text-align: center;">
    <img src="https://media.licdn.com/dms/image/v2/D4E0BAQE4bCQaEBYDUQ/company-logo_200_200/company-logo_200_200/0/1728590235264/hobotacademy_logo?e=1738195200&v=beta&t=0DiMS1wnJYE6nkBjL237Lh3mTm8GKEy_s65hG_yiTSs" alt="Hobot Academy Logo" width="200"/>
</div>

<h1 style="text-align: center;">Python</h1>
<h2 style="text-align: center;">Session 7</h2>
<h3 style="text-align: center;">NumPy</h3>
<h3 style="text-align: center;">Zahra Amini</h3>

<div style="width: 100%; text-align: center;">
    <table style="margin: 0 auto;">
        <tr>
            <td>
                <a href="https://t.me/hobotacademy">Telegram</a><br>
                <a href="https://www.linkedin.com/company/hobotacademy">LinkedIn</a><br>
                <a href="https://www.youtube.com/@AcademyHobot">YouTube</a><br>
            </td>
            <td>
                <a href="https://github.com/hobotacademy">GitHub</a><br>
                <a href="https://www.kaggle.com/aminizahra">Kaggle</a><br>
                <a href="https://www.instagram.com/hobot.academy/">Instagram</a><br>
            </td>
        </t>
    </table>
</div>
    </table>
</div>
    </table>
</div>

<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

**What is NumPy and Why is it Important?**<br><br>
- NumPy (Numerical Python) is a powerful library for numerical and scientific computing in Python.
- While Python lists are general-purpose, NumPy arrays are optimized for numerical operations, offering better performance.<br><br>

- **Why use NumPy?**<br>
    - Efficient matrix computations.<br>
    - Handling large datasets in numerical formats.<br>
    - Foundation for other advanced libraries like Pandas, TensorFlow, and Scikit-learn.
</div>


## 1. Installing NumPy

In [3]:
# pip install numpy

In [7]:
# pip show numpy

## 2. Importing NumPy

In [9]:
import numpy as np

## What is an Array and How is it Different from a Python List?
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">


**Python List**: A general-purpose data type that can store mixed data types (e.g., numbers, strings).<br><br>

**NumPy Array**:<br>
- **Homogeneous**: All elements must be of the same data type.<br>
- Optimized for numerical and scientific computations.<br>
- Faster than Python lists for large datasets.
</div>


In [11]:
my_list = [1, 2, 3, 4]

In [13]:
my_list

[1, 2, 3, 4]

In [15]:
np.array(my_list)

array([1, 2, 3, 4])

In [17]:
np.array([5, 6, 7, 8])

array([5, 6, 7, 8])

## 3. Basic Operations on Arrays

### Element-wise Addition and Multiplication

#### 🔸Addition:

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [21]:
a + b

array([5, 7, 9])

In [25]:
# np.array([1, 2,3, 4]) + np.array([5, 6, 7])

#### 🔸Multiplication:

In [27]:
a * b # 1 * 4, 2 * 5, 3 * 6

array([ 4, 10, 18])

## 4. Slicing Arrays

In [29]:
c = np.array([10, 20, 30, 40, 50])

In [31]:
c[1:4]

array([20, 30, 40])

## 5. NumPy Functions

### Zeros: Creates an array filled with zeros

In [33]:
zero_array = np.zeros(6)

In [35]:
zero_array

array([0., 0., 0., 0., 0., 0.])

In [37]:
zero_array.shape

(6,)

In [67]:
zero_array.ndim

1

In [39]:
zero_array2 = np.zeros((3, 3))
zero_array2

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [41]:
zero_array2.shape

(3, 3)

In [43]:
zero_array3 = np.zeros((2, 3))
zero_array3

array([[0., 0., 0.],
       [0., 0., 0.]])

### Ones: Creates an array filled with ones

In [45]:
np.ones((3, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

### arange: Creates an array with evenly spaced values within a specified range

In [47]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.arange(0, 10, 2) #start, end, step

array([0, 2, 4, 6, 8])

### linspace: Creates an array with a specific number of evenly spaced values

In [51]:
np.linspace(0, 1, 5) #start, end, num of points

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

## 6. Array Shape and Dimensions

### Checking Shape and Dimensions
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

- <code>array.shape</code>: Returns the shape of the array (rows, columns).<br>
- <code>array.ndim</code>: Returns the number of dimensions of the array.
</div>

In [53]:
array = np.array([[1, 2], [3, 4], [5, 6]])
array

array([[1, 2],
       [3, 4],
       [5, 6]])

In [55]:
array.shape

(3, 2)

In [57]:
array.ndim

2

<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

**Reshaping Arrays**: Use <code>array.reshape()</code> to change the shape of an array.
</div>


In [59]:
original = np.arange(1, 10)
original

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [61]:
original.reshape((3, 3))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [65]:
# original.reshape((3, 4))

## 7. Indexing and Slicing Arrays

### Slicing 1D Arrays

In [71]:
c

array([10, 20, 30, 40, 50])

In [73]:
c[2:4]

array([30, 40])

### Slicing 2D Arrays

In [75]:
array_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
array_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [77]:
array_2d[1:, 0:2]

array([[4, 5],
       [7, 8]])

### Boolean Indexing for Filtering: Use conditions to filter elements

In [79]:
array = np.array([1, 2, 3, 4, 5, 6])

In [81]:
array%2 == 0

array([False,  True, False,  True, False,  True])

In [83]:
array[array%2 == 0]

array([2, 4, 6])

## 8. Operations on Arrays

### Element-wise Operations
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Perform arithmetic operations directly between arrays, element by element:<br>
- Addition (<code>+</code>)<br>
- Subtraction (<code>-</code>)<br>
- Multiplication (<code>*</code>)<br>
- Division (<code>/</code>)
</div>


In [85]:
a

array([1, 2, 3])

In [87]:
b

array([4, 5, 6])

In [89]:
a + b

array([5, 7, 9])

In [91]:
a - b

array([-3, -3, -3])

In [93]:
a * b

array([ 4, 10, 18])

In [95]:
a / b

array([0.25, 0.4 , 0.5 ])

### Broadcasting
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Broadcasting allows NumPy to perform operations between arrays of different shapes by automatically expanding their dimensions when possible.
</div>


In [97]:
a

array([1, 2, 3])

In [99]:
d = 2
d

2

In [101]:
a * d

array([2, 4, 6])

#### With different array dimensions:

In [103]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

In [105]:
a + b

array([[2, 4, 6],
       [5, 7, 9]])

## 9. Aggregation Functions
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

NumPy provides several functions to calculate common statistics across an array, allowing us to efficiently analyze data. These functions are useful for summarizing information and performing quick calculations on datasets.<br><br>

Here are a few common aggregation functions:<br><br>
- **sum()**: Calculates the total sum of all elements in the array.<br>
- **mean()**: Returns the average (mean) value of the array.<br>
- **std()**: Computes the standard deviation, measuring the spread of values from the mean.<br>
- **min()**: Finds the smallest value in the array.<br>
- **max()**: Finds the largest value in the array.<br><br>
</div>


In [107]:
array = np.array([1, 2, 3, 4])
np.sum(array)

10

In [109]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [111]:
np.sum(a)

21

In [113]:
np.sum(a, axis=1) #row

array([ 6, 15])

In [115]:
np.sum(a, axis=0) #column

array([5, 7, 9])

In [117]:
# sum / num
np.mean(array)

2.5

In [119]:
np.sum(array)/4

2.5

In [127]:
np.sum(array)/array.shape[0]

2.5

In [125]:
array.shape[0]

4

In [131]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [129]:
np.max(a)

6

In [135]:
np.min(a, axis=0)

array([1, 2, 3])

In [137]:
# np.std(a)

## 10. Linear Algebra Operations

### Dot Product: Compute the inner product of two arrays:

In [139]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [143]:
a * b

array([ 4, 10, 18])

In [141]:
np.dot(a, b)

32

### Matrix Multiplication: Use the `@` operator or `np.dot()` for matrix multiplication:

In [145]:
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

In [147]:
np.dot(matrix1, matrix2)

array([[19, 22],
       [43, 50]])

In [149]:
matrix1 @ matrix2

array([[19, 22],
       [43, 50]])

### Transpose: Use `array.T` to transpose an array:

In [151]:
matrix = np.array([[1, 2], [3, 4]])
matrix

array([[1, 2],
       [3, 4]])

In [153]:
matrix.T

array([[1, 3],
       [2, 4]])

In [161]:
m1 = np.array([[1, 2, 3], [4, 5, 6]])
m2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
# m1 @ m2

In [159]:
m1 @ m2.T

array([[ 14,  32,  50,  68],
       [ 32,  77, 122, 167]])

## 11. Advanced Indexing and Array Manipulation

### Fancy Indexing
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">
Fancy indexing allows you to access or rearrange elements using arrays of indices.
</div>


#### Access Specific Elements:

In [163]:
array = np.array([10, 20, 30, 40, 50])
indx = [0, 2, 4]
array[indx]

array([10, 30, 50])

#### Reordering Elements:

In [165]:
array = np.array([5, 10, 15, 20, 25])
array

array([ 5, 10, 15, 20, 25])

In [167]:
ord = [4, 0, 3, 1]
array[ord]

array([25,  5, 20, 10])

### Merging Arrays
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Combine arrays horizontally or vertically using the following methods:
</div>

**Horizontal Stacking** (`np.hstack`): Combines arrays side by side.

In [169]:
array1 = np.array([1, 2, 3])
array2 = np.array([4, 5, 6])

np.hstack((array1, array2))

array([1, 2, 3, 4, 5, 6])

In [171]:
np.hstack((array2, array1))

array([4, 5, 6, 1, 2, 3])

**Vertical Stacking** (`np.vstack`): Combines arrays row by row.

In [173]:
np.vstack((array1, array2))

array([[1, 2, 3],
       [4, 5, 6]])

### Splitting Arrays
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Split arrays into smaller arrays using <code>np.split</code> and its variants:
</div>

**General Split** (`np.split`):

In [175]:
array = np.array([1, 2, 3, 4, 5, 6])

In [179]:
np.split(array, 6)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

**Horizontal Split** (`np.hsplit`): For splitting columns in 2D arrays.

In [181]:
array = np.array([[1, 2, 3], [4, 5, 6]])
np.hsplit(array, 3)

[array([[1],
        [4]]),
 array([[2],
        [5]]),
 array([[3],
        [6]])]

**Vertical Split** (`np.vsplit`): For splitting rows in 2D arrays.

In [185]:
np.vsplit(array, 2)

[array([[1, 2, 3]]), array([[4, 5, 6]])]

### Copy vs. View
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Understanding the difference between deep and shallow copies is crucial when manipulating arrays.
</div>

**View (Shallow Copy):** Modifies the original array as they share the same data.

In [187]:
array = np.array([1, 2, 3])
v = array.view()

In [189]:
v

array([1, 2, 3])

In [191]:
v[0] = 99
v

array([99,  2,  3])

In [193]:
array

array([99,  2,  3])

**Deep Copy:** Creates a completely independent copy.

In [195]:
cop = array.copy()
cop[0]=11
cop

array([11,  2,  3])

In [197]:
array

array([99,  2,  3])

## 12. Working with Random Data

### Uniform Distribution
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

- Generate random numbers between 0 and 1 (default) or within a specific range.
</div>

`np.random.rand` (0 to 1, uniform distribution):

In [199]:
np.random.rand(5)


array([0.23445231, 0.62900905, 0.32477936, 0.06781286, 0.78168449])

`np.random.uniform` (custom range):

In [201]:
np.random.uniform(1, 10, size=5)

array([4.90052992, 4.63612404, 8.59530858, 7.18963884, 8.98068171])

### Normal Distribution
<div style="background-color: #dafbe1; border-left: 5px solid #34c759; padding: 10px;">

Generate random numbers with a bell-curve (Gaussian) distribution.
</div>

`np.random.randn` (mean = 0, std deviation = 1):

In [205]:
a = np.random.randn(5)

In [211]:
a

array([-1.2731556 , -0.14949293, -0.5678499 ,  0.15432968, -2.25438932])

In [209]:
sum(a)/5

-0.8181116152894179

`np.random.normal` (custom mean and std deviation):

In [215]:
b = np.random.normal(loc=50, scale=10, size=5)

In [217]:
b

array([36.89548828, 54.12300733, 43.12789718, 39.85565802, 59.98048263])

In [219]:
np.sum(b)/5

46.796506687994636